name: CI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Backend Install
        run: yarn install

      - name: Backend Lint
        run: yarn run lint

      - name: Build Node.js Project
        if: ${{ success() }}
        run: yarn run build
